### PR TITLE
Fix GroupIcons toggle

### PR DESCRIPTION
**Pull request by expung3d**

### CODE REVIEW

**Comment by expung3d** [comment]
Fixes the toggle checkbox on the map. Before the toggle would have effect only while the map was open. The next time the map is opened the icons would appear again.

**Review by Chrisdw1002 — APPROVED** [review]
Looks good. I'll push it to the workshop.

**Comment by Chrisdw1002** [comment]
> Fixes the toggle checkbox on the map. Before the toggle would have effect only while the map was open. The next time the map is opened the icons would appear again.

Thanks for fixing it btw,

**Comment by expung3d** [comment]
Of course, I'll try to fix other issues I spot

**Pull request merged**
